config/routes.rb
CcroSurvey::Application.routes.draw do
  resources :answers

  resources :questions

  resources :surveys

  resources :responses

  resources :users
  resource :sessions
  resources :reports
  
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  
  match 'invite/:id' => 'surveys#invite_user', :as => 'invite'

  root :to => 'sessions#new'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :responses
  
  validates :option, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    render :text => "Explosion!", :status => 403
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json





  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer.question, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end







  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'answers/form' %>

<%= link_to 'Back', :back %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Option:</b>
  <%= @answer.option %>
</p>

<p>
  <b>Question:</b>
  <%= @answer.question %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>