config/routes.rb
CcroSurvey::Application.routes.draw do
  resources :answers

  resources :questions

  resources :surveys

  resources :responses

  resources :users
  resource :sessions
  resources :reports
  
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  
  match 'invite/:id' => 'surveys#invite_user', :as => 'invite'

  root :to => 'sessions#new'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  has_many :responses, :through => :questions
  has_many :users, :through => :responses, :uniq => true
  
  validates :name, :presence => true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  before_filter :require_user, :only => [:show, :index]
  before_filter :require_admin, :only => [:edit, :destroy, :update]
  
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to edit_survey_path(@survey), notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
  
  def invite_user
    @survey = Survey.find(params[:id])
    UserMailer.survey_invite(@survey, User.first).deliver
    redirect_to :back
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1><%= @survey.name %></h1>


<div>
	<% @survey.questions.each do |question| %>
  		<label><b><%= question.prompt %></b></label>
		<% question.answers.each do |a| %>
		   <label class="radio">
  			<%= radio_button_tag a, a %><%= a.option %><br />
  			</label>
		<% end %>
  		<%= link_to "Delete", question_path(question), :method => "delete" %><br /><br />
	<% end %>
</div>

<br />



<%= link_to "New Question", {:controller => "questions", :action => "new", :survey_id => @survey.id}, :class => 'btn btn-primary' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>
<br />
<br />

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>
<br />
<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.name %> <em>(<%= survey.users.count.to_s + " respondents" if survey.users %>)</em> <%= raw('<span class="label label-important">NEW</span>') if survey.responses.last && survey.responses.last.created_at > 5.hours.ago %></td>
    <td class="span2">
      <% if current_user.admin %>
      <div class="btn-group">
        <a href="<%= survey_path(survey) %>" class="btn">Show</a>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><%= link_to 'Report', report_path(survey.id) %></li>
            <li><%= link_to 'Invite User', invite_path(survey.id) %></li>
           <li><%= link_to 'Edit', edit_survey_path(survey) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Delete', survey, confirm: 'Are you sure?', method: :delete %></li>
        </ul>
      </div>
      <% else %>
        <%= link_to "Take Survey", survey, :class => 'btn'%>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path, :class => 'btn btn-primary' %>

app/views/surveys/new.html.erb
<h1>New survey</h1>
<br />

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @survey.name %></h1><br />

	<%= form_tag responses_path, { :method => 'post', :class => 'well' } do %>
		<% @survey.questions.each do |question| %>
				<%= hidden_field_tag "[response]#{question.id}[question_id]", question.id %>
		  		<label><b><%= question.prompt %></b></label>
				<% unless question.answers.count == 0 %>
				
					<% question.answers.each do |a| %>
					    <label class="radio">
			  			<%= radio_button_tag "[response]#{question.id}[answer_id]", a.id, Response.find_or_initialize_by_user_id_and_question_id(current_user,question).answer_id == a.id %><%= a.option %><br />
					    </label>
					<% end %>
				<% else %>
		
					<%= text_area_tag "[response]#{question.id}[message]",  Response.find_or_initialize_by_user_id_and_question_id(current_user,question).message %>
			
				<% end %>
		  <br />
		<% end %>
		<br />
		<br />
		<%= submit_tag 'submit', :class => 'btn-primary' %>
		<%= link_to 'Back', surveys_path %>
	<% end %>
</div>

<br />
<br />