config/routes.rb
CcroSurvey::Application.routes.draw do
  resources :answers

  resources :questions

  resources :surveys

  resources :responses

  resources :users
  resource :sessions
  resources :reports
  
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  
  match 'invite/:id' => 'surveys#invite_user', :as => 'invite'

  root :to => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CcroSurvey</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
<% if current_user %> 
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">CCRO Survey</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Surveys", surveys_path  %></li>
                <% if current_user.admin %>
                  <li><%= link_to "Users", users_path  %></li>
                <% end %>
                <li><%= link_to "Log Out", logout_path  %></li>
            </ul>
            <p class="navbar-text pull-right">Logged in as <%= current_user.email if current_user %></p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<% end %>
    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            
        </div><!--/row-->
      </div><!--/content-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>